# Generated by Django 5.0.1 on 2024-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='length_of_line',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='generated_prompt',
            field=models.TextField(null=True),
        ),
    ]
