# Generated by Django 5.0.1 on 2024-01-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_app', '0003_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='chunks',
        ),
        migrations.RemoveField(
            model_name='document',
            name='embeds',
        ),
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.TextField()),
                ('embed', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt_app.document')),
            ],
        ),
    ]
